# AUTOGENERATED! DO NOT EDIT! File to edit: ../../src/platform/qcircuit_metrics.ipynb.

# %% auto 0
__all__ = ['Unitary_FrobeniusNorm']

# %% ../../src/platform/qcircuit_metrics.ipynb 3
from ..imports import *

# %% ../../src/platform/qcircuit_metrics.ipynb 5
# class Unitary_FrobeniusNorm:
#     #defined in https://arxiv.org/pdf/2106.05649.pdf
    
#     @staticmethod
#     def distance(approx_U: torch.tensor, target_U: torch.tensor):
#         d = 0.5 * torch.linalg.matrix_norm((approx_U-target_U), ord="fro")**2
#         return d
        
#     @staticmethod
#     def name():
#         return "Frobenius-Norm"


class Unitary_FrobeniusNorm:
    @staticmethod
    def distance(approx_U: torch.tensor, target_U: torch.tensor):
        d = target_U.shape[-1]
        s = torch.trace(target_U.conj().T @ approx_U)
        return d - torch.abs(s)                   # 相位不变
    @staticmethod
    def name():
        return "Frobenius-Norm (phase-free)"

class Unitary_ProcessFidelity:
    @staticmethod
    def fidelity(approx_U: torch.tensor, target_U: torch.tensor):
        d = target_U.shape[-1]
        s = torch.trace(target_U.conj().T @ approx_U)
        return (torch.abs(s) ** 2) / (d * d)      # ∈ [0,1]

    @staticmethod
    def loss(approx_U: torch.tensor, target_U: torch.tensor):
        return 1.0 - Unitary_ProcessFidelity.fidelity(approx_U, target_U)

    @staticmethod
    def name():
        return "Process fidelity (phase-free)"
